#!/usr/bin/env bash

# Folder that contains results folder of test selection
PEASS_REPOS="./"

# last line of file needs to be empty
filename=./excludes_tomcat.txt
while read -r line; do
  if [[ ! -z "$line" && ! $line =~ ^#.* ]]; then
    excluded="$excluded -excludes $line"
  fi
done < "$filename"

if [ "$1" = "select" ]; then
  ./tomcat-analysis select -folder ../tomcat/ -classFolder java:src/main/java:webapps/examples/WEB-INF/classes:webapps/examples/jsp/plugin/applet -testClassFolder test \
    -testExecutor de.stro18.peass_ant.executor.AntTestExecutor -testTransformer de.dagere.peass.testtransformation.JUnitTestTransformer \
    -startcommit fa64c162a505bf36c0335d713dea5606f9185dc2 -endcommit 6b8aeaf80860dd48d5ddd44e866fea5d6072ded3 \
    -threads 2 -traceSizeInMb 10 -timeout 2 \
    -includes org.apache.* -forbiddenMethods org.apache.catalina.startup.Tomcat#start -excludes '*$*' $excluded
  ./peasstomcat createScript
elif [ "$1" = "measure" ]; then
  ./tomcat-analysis measure -folder ../tomcat/ -classFolder java:src/main/java:webapps/examples/WEB-INF/classes:webapps/examples/jsp/plugin/applet -testClassFolder test \
    -executionfile ${PEASS_REPOS}results/traceTestSelection_tomcat.json \
    -testExecutor de.stro18.peass_ant.executor.AntTestExecutor -testTransformer de.dagere.peass.testtransformation.JUnitTestTransformer -statisticTest T_TEST \
    -startcommit fa64c162a505bf36c0335d713dea5606f9185dc2 -endcommit 6b8aeaf80860dd48d5ddd44e866fea5d6072ded3  \
    -vms 100 -iterations 400 -warmup 400 -repetitions 60 -measurementStrategy PARALLEL -timeout 2 -type1error 0.01
  ./tomcat-analysis getchanges -data ../tomcat_peass/ -executionfile ${PEASS_REPOS}results/traceTestSelection_tomcat.json -type1error 0.01
elif [ "$1" = "searchcause" ]; then
   rm -r -f ../tomcat_peass/projectTemp
  ./tomcat-analysis searchcause -folder ../tomcat/ -classFolder java:src/main/java:webapps/examples/WEB-INF/classes:webapps/examples/jsp/plugin/applet -testClassFolder test \
    -executionfile ${PEASS_REPOS}results/traceTestSelection_tomcat.json \
    -testExecutor de.stro18.peass_ant.executor.AntTestExecutor -testTransformer de.dagere.peass.testtransformation.JUnitTestTransformer \
    -commit 6b8aeaf80860dd48d5ddd44e866fea5d6072ded3 -test org.apache.catalina.core.TestApplicationSessionCookieConfig\#testSetDomainInitPhase \
    -vms 100 -iterations 400 -warmup 400 -repetitions 60 -measurementStrategy PARALLEL -timeout 10 -type1error 0.01
  ./peasstomcat visualizerca
elif [ "$1" = "createScript" ]; then
  ./tomcat-analysis createScript -executionfile ${PEASS_REPOS}results/traceTestSelection_tomcat.json > $results/runall.sh
elif [ "$1" = "measureSingle" ]; then
  ./tomcat-analysis measure -folder ../tomcat/ -classFolder java:src/main/java:webapps/examples/WEB-INF/classes:webapps/examples/jsp/plugin/applet -testClassFolder test \
    -executionfile ${PEASS_REPOS}results/traceTestSelection_tomcat.json \
    -testExecutor de.stro18.peass_ant.executor.AntTestExecutor -testTransformer de.dagere.peass.testtransformation.JUnitTestTransformer -statisticTest T_TEST \
    -commit $2 -test $3  \
    -vms 100 -iterations 400 -warmup 400 -repetitions 60 -measurementStrategy PARALLEL -timeout 2 -type1error 0.01
elif [ "$1" = "getchanges" ]; then
  ./peasstomcat clean
  ./tomcat-analysis getchanges -data ../tomcat_peass/ -executionfile ${PEASS_REPOS}results/traceTestSelection_tomcat.json -type1error 0.01
elif [ "$1" = "clean" ]; then
  rm -r ../tomcat_peass/clean
  ./tomcat-analysis clean -data ../tomcat_peass/ -executionfile ${PEASS_REPOS}results/traceTestSelection_tomcat.json
elif [ "$1" = "searchcauseParameterized" ]; then
  rm -r -f ../tomcat_peass/projectTemp
  ./tomcat-analysis searchcause -folder ../tomcat/ -classFolder java:src/main/java:webapps/examples/WEB-INF/classes:webapps/examples/jsp/plugin/applet -testClassFolder test \
    -executionfile ${PEASS_REPOS}results/traceTestSelection_tomcat.json \
    -testExecutor de.stro18.peass_ant.executor.AntTestExecutor -testTransformer de.dagere.peass.testtransformation.JUnitTestTransformer \
    -commit $2 -test $3 \
    -vms 100 -iterations 400 -warmup 400 -repetitions 60 -measurementStrategy PARALLEL -timeout 10 -type1error 0.01
elif [ "$1" = "visualizerca" ]; then
  ./tomcat-analysis visualizerca -data ../tomcat_peass/ -propertyFolder ${PEASS_REPOS}results/properties_tomcat/
fi